FROM flavorjones/truffleruby:nightly

ARG NOKOGIRI_USE_SYSTEM_LIBRARIES=true

RUN echo "NOKOGIRI_USE_SYSTEM_LIBRARIES = $NOKOGIRI_USE_SYSTEM_LIBRARIES"

ENV RAILS_ENV=production \
    NODE_ENV=production \
    RAILS_SERVE_STATIC_FILES=true \
    RAILS_LOG_TO_STDOUT=true \
    RACK_TIMEOUT_SERVICE_TIMEOUT=60 \
    BUNDLE_SILENCE_ROOT_WARNING=1 \
    BUNDLE_BUILD__SASSC=--disable-march-tune-native 

RUN mkdir /app
WORKDIR /app

#RUN apt-get update && apt-get install -y curl gnupg2 git libpq-dev

# Install node, leaving as few artifacts as possible
RUN apt-get update && apt-get install apt-transport-https && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get update && \
    apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends yarn nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/dpkg.log

# install NPM packages removign artifacts
COPY package.json yarn.lock ./
RUN yarn install && yarn cache clean

COPY Gemfile Gemfile.lock ./
RUN bundle install --without development
