FROM after-bundle-install:latest

COPY . .

#ENV TRUFFLERUBYOPT='--experimental-options --engine.CompilerThreads=0'

RUN bundle exec rake assets:precompile RAILS_ENV=production NODE_ENV=production SECRET_KEY_BASE=stubbed SKIP_REDIS=true
