FROM after-assets-precompile:latest

# Create symlinks for CSS files without digest hashes for use in error pages
RUN bundle exec rake assets:symlink_non_digested SECRET_KEY_BASE=stubbed SKIP_REDIS=true

EXPOSE 3000

ENV RUBYOPT=
ENTRYPOINT ["bundle", "exec"]
CMD ["rails", "server"]
