FROM ubuntu:18.04

ENV RAILS_ENV=production \
    NODE_ENV=production \
    RAILS_SERVE_STATIC_FILES=true \
    RAILS_LOG_TO_STDOUT=true \
    RACK_TIMEOUT_SERVICE_TIMEOUT=60 \
    BUNDLE_SILENCE_ROOT_WARNING=1 \
    BUNDLE_BUILD__SASSC=--disable-march-tune-native 

RUN apt-get update

RUN apt-get install -y locales
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8

RUN  apt-get -y install tar curl make gcc libssl-dev time libxml2-dev libxslt-dev

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y tzdata

RUN curl -L https://github.com/ruby/truffleruby-dev-builder/releases/latest/download/truffleruby-head-ubuntu-18.04.tar.gz | tar xz
ENV PATH="/truffleruby-head/lib/llvm-toolchain/bin:/truffleruby-head/bin:$PATH"
RUN "/truffleruby-head/lib/truffle/post_install_hook.sh"
RUN which ruby
RUN ruby --version
RUN gem install rails

# Install node, leaving as few artifacts as possible
RUN apt-get update && apt-get install apt-transport-https && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get update && \
    apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends yarn nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/dpkg.log

RUN apt-get update
RUN apt-get -y install libsqlite3-dev

RUN apt update
RUN apt install -y git 
RUN git --version

RUN rails new blog
RUN cd blog
RUN rails server 
